### ISSUE TITLE
Extracting Non-B-DNA from PacBio Reads

### ISSUE THREAD

**Issue by venkata14** [makovalab-psu/nonBKinetics#2]
Hello! Thank you for this repository!

I apologize, I am very new to this and saying I am confused is an understatement. I am trying to determine regions of Non-B-DNA in the _Drosophila melanogaster_ genome using PacBio reads. 

I understand I have to follow the guide for "Figure 2" in this GitHub repository for my purposes but it is confusing me. I believe I understand how to extract the IPDs from my PacBio reads but I have trouble understanding the rest of the guide for determining Non-B-DNA. I have listed my questions down below!

1) When extracting IPDs using this command `ipdSummary.py $inp --reference ../dm6.fa --outfile ${inp}.idp`, I notice that the `.idp` is no longer used but `.pickle` files are used. Does ipdSummary.py create these `.pickle` files? (Sorry dumb question, I haven't run `ipdSummary.py` yet)

2) There is no Non-B-DNA database for the _D. melanogaster_ so would the analysis on this repository still work for my purposes?

3) Is there a guide that I am missing because I do not understand where some of these files are coming from like the "all.per1.TRs.bed.10" file or like what Di, Tri and Tetra means from "Repeat for Di, Tri and Tetra".

4) For the programs that run IWT (`load_IPD_data.r`, `IWT_IPD.r `, `feature_length_IPD.r `), do they take no input but take in "datasets.txt" from the directory? I do not exactly understand how they are working.

5) Also from my limited understanding of IWT, it kind of behaves like the Kolmogorov–Smirnov test to see if two functional data intervals are similar or different (or I could just be completely off). If that's the case, does that mean I do not need the Non-B-DNA annotation to determine if something is B-DNA or Non-B-DNA as the Non-B-DNA annotation does not have IPDs along with it? Is the purpose of the Non-B-DNA annotation to simply determine what kind of Non-B-DNA the IWT analysis found?

I know this is a lot so thank you very much for your time!
Venkata

**Comment by marziacremona** [comment]
Hello Venkata, 

I can answer to part of your questions, I leave the rest to @wilfriedguiblet. 

> I am trying to determine regions of Non-B-DNA in the Drosophila melanogaster genome using PacBio reads. I understand I have to follow the guide for "Figure 2" in this GitHub repository for my purposes but it is confusing me.

The code in this repository doesn't find non-B DNA regions from PacBio reads. The code allows you to compare IPDs from PacBio reads between non-B DNA regions and control regions, but you need to know which regions belong to these two groups in advance (in other words, you need to have non-B DNA annotations and then you can define as control the DNA regions with no overlap with non-B DNA annotations). 

> There is no Non-B-DNA database for the D. melanogaster so would the analysis on this repository still work for my purposes?

As I said above, you need to have non-B DNA annotations in order to run the rest of the analysis. For G4s there exist multiple tools that allow you to computationally predict G4 regions given the genome sequence. For other types of non-B DNA, I guess you can use their definition to find them in the D. melanogaster genome.  

> For the programs that run IWT (load_IPD_data.r, IWT_IPD.r , feature_length_IPD.r ), do they take no input but take in "datasets.txt" from the directory? I do not exactly understand how they are working.

You are right that the script `load_IPD_data.r` takes as input the file "datasets.txt", as well as the file "features_datasets_forward.txt". First, you need to create the region files and the corresponding IPD files following the `Steps to prepare IPD and Depth data in PacBio` and `Steps to prepare IWT input`. These steps will create two files "*_filtered" and "*_filtered_length" for each type of non-B DNA regions and for control regions. The file "datasets.txt" needs to contain the IDs, names and file names "*_filtered", while the file "features_datasets_forward.txt" will contain a single row for IPD data, with ID, name and files names "*_filtered_length". I suggest you to check IWTomics vignette [here](https://bioconductor.org/packages/release/bioc/vignettes/IWTomics/inst/doc/IWTomics.pdf), in particular Section 2 (Importing data).

> Also from my limited understanding of IWT, it kind of behaves like the Kolmogorov–Smirnov test to see if two functional data intervals are similar or different (or I could just be completely off). If that's the case, does that mean I do not need the Non-B-DNA annotation to determine if something is B-DNA or Non-B-DNA as the Non-B-DNA annotation does not have IPDs along with it? Is the purpose of the Non-B-DNA annotation to simply determine what kind of Non-B-DNA the IWT analysis found?

Kolmogorov–Smirnov tests for equality of two continuous distributions, IWT tests for equality of two functional distributions. In this sense yes, their purpose is similar. The main difference is that IWT is for curves, so it tests for differences between two groups of curves (not between two groups of numbers). IWT doesn't found the non-B DNA for you. You need to define the two groups to compare (non-B DNA of a certain type and control) in advance, then IWT test for differences in IPDs between these two groups. For more details, you can check [IWTomics paper](https://doi.org/10.1093/bioinformatics/bty090).

**Comment by venkata14** [comment]
Hello Dr. Cremona,

Thank you so much for your response!

My goal is to use the IWT test to determine regions of Non-B-DNA in the  _D. melanogaster_  genome (So like I do not need to know exactly what type of non-B-DNA). And since I do not have Non-B-DNA annotations as controls for the IWT test, could I use controls that show the IPD values for normal B-DNA and run it on my data to determine regions that are not B-DNA?

**Comment by marziacremona** [comment]
Hello again, 

No, that's not possible. The test needs two groups of pre-defined regions to compare. It doesn't allow you to discover non-B DNA regions.

I really suggest you to take the D. melanogaster reference genome and look for possible non-B DNA motifs directly within the genome. 
> For G4s there exist multiple tools that allow you to computationally predict G4 regions given the genome sequence. For other types of non-B DNA, I guess you can use their definition to find them in the D. melanogaster genome.

After you have the annotations, you can extract IPDs and run IWT to see if these regions show increase in IPDs or not, so you can use the IPDs to "confirm" the presence of non-B DNA in the annotated regions.

**Comment by wilfriedguiblet** [comment]
Hello Venkata,

I believe Marzia already answered most of your questions, but here are some additional answers:

> My goal is to use the IWT test to determine regions of Non-B-DNA in the D. melanogaster genome 

For annotations of non-B DNA, I suggest you visit the non-B DB page: https://nonb-abcc.ncifcrf.gov/apps/Query-GFF/default. The annotation of D. melanogaster is not available but the non-B DNA Motif Search Tool is. You can use it to make your own annotation.

> When extracting IPDs using this command ipdSummary.py $inp --reference ../dm6.fa --outfile ${inp}.idp, I notice that the .idp is no longer used but .pickle files are used. Does ipdSummary.py create these .pickle files? (Sorry dumb question, I haven't run ipdSummary.py yet)

Yes, ipdSummary.py outputs a .pickle file.

> Is there a guide that I am missing because I do not understand where some of these files are coming from like the "all.per1.TRs.bed.10" file or like what Di, Tri and Tetra means from "Repeat for Di, Tri and Tetra".

These files were created in a previous study (DOI: 10.1101/gr.185892.114). They are microsatellite annotations.

**Comment by venkata14** [comment]
Sorry, forgot to close this a long time ago. Thank you for your help!
